# Generated by Django 3.0.6 on 2020-07-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotSearchWords',
        ),
        migrations.AddField(
            model_name='goods',
            name='ali_url',
            field=models.URLField(default='', verbose_name='商品阿里巴巴链接'),
        ),
        migrations.AddField(
            model_name='goods',
            name='min_order',
            field=models.FloatField(default=0, verbose_name='最小起订量'),
        ),
        migrations.AddField(
            model_name='goods',
            name='pic_url',
            field=models.URLField(default='', verbose_name='商品展示图url'),
        ),
        migrations.AddField(
            model_name='goods',
            name='price',
            field=models.FloatField(default=0, verbose_name='单价'),
        ),
        migrations.AddField(
            model_name='goods',
            name='unit',
            field=models.CharField(choices=[(1, 'Piece'), (2, 'Meter'), (3, 'Roll')], default=1, help_text='单位', max_length=10, verbose_name='单位'),
        ),
    ]
