# Generated by Django 3.0.6 on 2020-07-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20200703_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='unit',
            field=models.IntegerField(choices=[(1, 'Piece'), (2, 'Meter'), (3, 'Roll')], default=1, max_length=10, verbose_name='单位'),
        ),
    ]
