# Generated by Django 3.0.6 on 2020-07-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20200703_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='unit',
            field=models.IntegerField(choices=[('Pieces', 'Piece'), ('Meters', 'Meter'), ('Rolls', 'Roll'), ('Kilograms', 'Kilogram')], default=1, verbose_name='单位'),
        ),
    ]
