# Generated by Django 3.0.6 on 2020-07-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20200707_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='unit',
            field=models.CharField(choices=[('Pieces', 'Piece'), ('Meters', 'Meter'), ('Rolls', 'Roll'), ('Kilograms', 'Kilogram')], default='Pieces', max_length=10, verbose_name='单位'),
        ),
    ]
